# Site settings
title: qaqRose Blog
SEOTitle: qaqRose的博客 | qaqRose Blog
header-img: img/you-name.jpg
email: singleqaq@gmail.com
description: ""
keyword: ""
url: "qaqrose.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:     none
#zhihu_username:     none
#github_username:    none
#twitter_username:   none
#facebook_username:  none



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["Gemfile", "Gemfile.lock", "toc.html" ,"less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
# duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: eb4e16e7b36b0d732d7dc767b036bd7a
# Google Analytics
#ga_track_id: ''            # Format: UA-xxxxxx-xx
#ga_domain: qaqrose.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "日拱一卒，功不唐捐"
#sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 2              # A tag will be featured if the size of it is more than this condition value



# Friends
# friends: [
#     {
#         title: "Foo",
#         href: "#"
#     },{
#         title: "Bar",
#         href: "#"
#     },{
#         title: "Example Friends",
#         href: "#"
#     },{
#         title: "It helps SEO",
#         href: "#"
#     }
# ]
